// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mujbtkehbgtufaapytue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11amJ0a2VoYmd0dWZhYXB5dHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzcyNTAsImV4cCI6MjA2NTgxMzI1MH0.bfyuCZ-gY-qwzV0lyewC1xrIxHaO1AiFevzsySIwqrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);